name: SonarCloud

on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
      organization:
        required: true
        type: string
      sources:
        required: false
        type: string
      exclusions:
        required: false
        type: string
    secrets:
      sonar-cloud-token:
        required: true
      github-token:
        required: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.github-token }}  
        SONAR_TOKEN: ${{ secrets.sonar-cloud-token }}  
      with:
        args:
          -Dsonar.projectKey=${{ github.event.inputs.project-key }}
          -Dsonar.organization=${{ github.event.inputs.organization }}
          -Dsonar.sources=${{ github.event.inputs.sources }}
          -Dsonar.exclusions=${{ github.event.inputs.exclusions }}
